import { NextRequest, NextResponse } from "next/server"
import { auth } from "@/auth"
import { prisma } from "@/lib/prisma"
import { generateChat, ChatMessage } from "@/ai/orchestrator"

export async function POST(request: NextRequest) {
  try {
    const session = await auth()
    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const { messages, sessionId } = await request.json()
    if (!messages || !Array.isArray(messages)) {
      return NextResponse.json({ error: "Messages array required" }, { status: 400 })
    }

    const user = await prisma.user.findUnique({
      where: { id: session.user.id },
      include: { company: true },
    })

    if (!user?.companyId) {
      return NextResponse.json({ error: "Company not found" }, { status: 400 })
    }

    // Fetch master data + business context in parallel
    const [clients, bankAccounts, invoiceSummary, catalogCount] = await Promise.all([
      prisma.customer.findMany({
        where: { companyId: user.companyId, deletedAt: null },
        select: { id: true, name: true, companyName: true, gstin: true, email: true, state: true },
      }),
      prisma.bankAccount.findMany({
        where: { companyId: user.companyId },
        select: { id: true, bankName: true, accountName: true, accountNumber: true, ifscCode: true, isDefault: true },
      }),
      prisma.invoice.groupBy({
        by: ["status"],
        where: { companyId: user.companyId, deletedAt: null },
        _count: { _all: true },
        _sum: { finalAmount: true, balanceDue: true },
      }),
      prisma.productCatalog.count({ where: { companyId: user.companyId, deletedAt: null, isActive: true } }),
    ])

    const overdueStat = invoiceSummary.find(s => s.status === "OVERDUE")
    const totalOutstanding = invoiceSummary
      .filter(s => ["SENT", "VIEWED", "PARTIALLY_PAID", "OVERDUE"].includes(s.status))
      .reduce((sum, s) => sum + (s._sum.balanceDue ?? 0), 0)
    const overdueCount = overdueStat?._count._all ?? 0
    const overdueAmount = overdueStat?._sum.balanceDue ?? 0
    const totalPaid = invoiceSummary.find(s => s.status === "PAID")?._sum.finalAmount ?? 0

    const businessSnapshot = `## Business Snapshot (as of ${new Date().toISOString().split("T")[0]})
- Outstanding: ₹${totalOutstanding.toLocaleString("en-IN")} | Overdue: ${overdueCount} invoices worth ₹${overdueAmount.toLocaleString("en-IN")}
- Paid revenue (all time): ₹${totalPaid.toLocaleString("en-IN")} | Active catalog items: ${catalogCount}`

    // Short-circuit greetings
    if (messages.length > 0) {
      const lastContent = messages[messages.length - 1].content.trim().toLowerCase()
      if (["hi", "hello", "hey"].includes(lastContent)) {
        const clientName = clients[0]?.companyName || clients[0]?.name || "your client"
        const bankName = bankAccounts.find(b => b.isDefault)?.bankName || bankAccounts[0]?.bankName || "your bank"
        const canned = `Hello! I'm your **AI Invoice Assistant**. I can help you:\n\n- 📄 **Create multi-item invoices** conversationally\n- 📊 **Analyze your business** — revenue, overdue, top customers\n- ✉️ **Draft professional emails**\n\nJust say something like:\n> *"Invoice Ravi Enterprises for web design ₹50,000 + GST 18% and hosting ₹5,000"*\n\nDefaults: **${clientName}** and **${bankName}**.`
        return NextResponse.json({ message: canned })
      }
    }

    // Construct system prompt
    const systemPrompt = `You are an expert AI Invoice Assistant for Open Invoice, a GST-compliant Indian invoicing platform.

Today's Date: ${new Date().toISOString().split("T")[0]}

${businessSnapshot}

## Client Master (use ONLY these IDs)
${JSON.stringify(clients, null, 2)}

## Company Bank Accounts
${JSON.stringify(bankAccounts, null, 2)}

## Invoice Creation Rules
- Support UNLIMITED line items per invoice
- Default GST: 18%; valid: 0, 5, 12, 18, 28
- Due Date default: 30 days after invoice date
- Use **markdown** in responses (bold, lists, tables)

## Invoice Preview (use markdown table)
| Item | HSN | Qty | Rate | GST% | Amount |
|------|-----|-----|------|------|--------|

## JSON Output (when user confirms)
\`\`\`json
{
  "clientId": "from-master",
  "bankAccountId": "from-master",
  "invoiceDate": "YYYY-MM-DD",
  "dueDate": "YYYY-MM-DD",
  "themeColor": "#1e40af",
  "notes": "Generated by AI Assistant",
  "items": [
    { "description": "string", "hsnSac": null, "quantity": 1, "rate": 50000, "discount": 0, "gstPercent": 18 }
  ]
}
\`\`\`

Never invent client or bank data. Be concise and proactively helpful.`

    const fullMessages: ChatMessage[] = [
      { role: "system", content: systemPrompt },
      ...messages
    ]

    const response = await generateChat({
      companyId: user.companyId,
      messages: fullMessages,
    })

    return NextResponse.json({ message: response })
  } catch (error) {
    console.error("AI Chat Error:", error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Internal Server Error" },
      { status: 500 }
    )
  }
}
